### ISSUE TITLE
Internal Server Error when saving a plot

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#88]
Logs from the staging server:

```
2018-01-12T02:08:52.180864172Z app[web.1]: Internal Server Error: /plot/9/edit/
2018-01-12T02:08:52.180872030Z app[web.1]: Traceback (most recent call last):
2018-01-12T02:08:52.180879941Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
2018-01-12T02:08:52.180889350Z app[web.1]:     response = get_response(request)
2018-01-12T02:08:52.180938572Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
2018-01-12T02:08:52.180963607Z app[web.1]:     response = self.process_exception_by_middleware(e, request)
2018-01-12T02:08:52.180972878Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
2018-01-12T02:08:52.181018582Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2018-01-12T02:08:52.181033139Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 69, in view
2018-01-12T02:08:52.181041968Z app[web.1]:     return self.dispatch(request, *args, **kwargs)
2018-01-12T02:08:52.181050262Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
2018-01-12T02:08:52.181060168Z app[web.1]:     return super().dispatch(request, *args, **kwargs)
2018-01-12T02:08:52.181107259Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
2018-01-12T02:08:52.181144074Z app[web.1]:     return super().dispatch(request, *args, **kwargs)
2018-01-12T02:08:52.181152882Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
2018-01-12T02:08:52.181161028Z app[web.1]:     return handler(request, *args, **kwargs)
2018-01-12T02:08:52.181213635Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 194, in post
2018-01-12T02:08:52.181223392Z app[web.1]:     return super().post(request, *args, **kwargs)
2018-01-12T02:08:52.181231758Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 141, in post
2018-01-12T02:08:52.181240483Z app[web.1]:     if form.is_valid():
2018-01-12T02:08:52.181248100Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 179, in is_valid
2018-01-12T02:08:52.181287092Z app[web.1]:     return self.is_bound and not self.errors
2018-01-12T02:08:52.181297112Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 174, in errors
2018-01-12T02:08:52.181302818Z app[web.1]:     self.full_clean()
2018-01-12T02:08:52.181307806Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 376, in full_clean
2018-01-12T02:08:52.181313323Z app[web.1]:     self._clean_fields()
2018-01-12T02:08:52.181318289Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 394, in _clean_fields
2018-01-12T02:08:52.181323780Z app[web.1]:     value = field.clean(value)
2018-01-12T02:08:52.181328803Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/fields.py", line 148, in clean
2018-01-12T02:08:52.181334195Z app[web.1]:     value = self.to_python(value)
2018-01-12T02:08:52.181339123Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/models.py", line 1245, in to_python
2018-01-12T02:08:52.181375275Z app[web.1]:     value = self.queryset.get(**{key: value})
2018-01-12T02:08:52.181382069Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 407, in get
2018-01-12T02:08:52.181387709Z app[web.1]:     (self.model._meta.object_name, num)
2018-01-12T02:08:52.181392821Z app[web.1]: gardenhub.models.MultipleObjectsReturned: get() returned more than one Garden -- it returned 2!
```

**Comment by alexgleason** [comment]
This was fixed in 36eca469f6b8726052da3922bb051531bcf8bbd8, caused by the edit garden form's queryset creating a union between the user's available gardens and the current garden being edited. In the case of an overlap it would give a MultipleObjectsReturned error.

**Comment by alexgleason** [comment]
Never mind, that did not fix it.

Apparently I've misused the [union](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#django.db.models.query.QuerySet.union) queryset method. It doesn't allow further filtering, so I'll have to create the queryset another way.

**Comment by alexgleason** [comment]
Finally resolved via e0bd6c649293e3af2da6d94c387f149eb238fe4e with a test in b0f440e7c7a8fe8a9d72b558498f3c403ce1cfc1.

**Comment by marykatefain** [comment]
This is still happening. Logs return:

```
root@candlewaster:~# dokku logs gardenhub
2018-02-03T18:21:38.891805554Z app[web.1]:     response = self.process_exception_by_middleware(e, request)
2018-02-03T18:21:38.891812911Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
2018-02-03T18:21:38.891820281Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2018-02-03T18:21:38.891856451Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 69, in view
2018-02-03T18:21:38.891867368Z app[web.1]:     return self.dispatch(request, *args, **kwargs)
2018-02-03T18:21:38.891874521Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
2018-02-03T18:21:38.891881858Z app[web.1]:     return super().dispatch(request, *args, **kwargs)
2018-02-03T18:21:38.891888831Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
2018-02-03T18:21:38.891896141Z app[web.1]:     return super().dispatch(request, *args, **kwargs)
2018-02-03T18:21:38.891903095Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
2018-02-03T18:21:38.891910295Z app[web.1]:     return handler(request, *args, **kwargs)
2018-02-03T18:21:38.891943438Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 194, in post
2018-02-03T18:21:38.891953701Z app[web.1]:     return super().post(request, *args, **kwargs)
2018-02-03T18:21:38.891960521Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 141, in post
2018-02-03T18:21:38.891967675Z app[web.1]:     if form.is_valid():
2018-02-03T18:21:38.891974411Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 179, in is_valid
2018-02-03T18:21:38.891981708Z app[web.1]:     return self.is_bound and not self.errors
2018-02-03T18:21:38.891988655Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 174, in errors
2018-02-03T18:21:38.891995961Z app[web.1]:     self.full_clean()
2018-02-03T18:21:38.892029308Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 376, in full_clean
2018-02-03T18:21:38.892038818Z app[web.1]:     self._clean_fields()
2018-02-03T18:21:38.892065108Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 394, in _clean_fields
2018-02-03T18:21:38.892071925Z app[web.1]:     value = field.clean(value)
2018-02-03T18:21:38.892077948Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/fields.py", line 148, in clean
2018-02-03T18:21:38.892116191Z app[web.1]:     value = self.to_python(value)
2018-02-03T18:21:38.892125355Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/models.py", line 1245, in to_python
2018-02-03T18:21:38.892131831Z app[web.1]:     value = self.queryset.get(**{key: value})
2018-02-03T18:21:38.892137845Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 407, in get
2018-02-03T18:21:38.892144258Z app[web.1]:     (self.model._meta.object_name, num)
2018-02-03T18:21:38.892150242Z app[web.1]: gardenhub.models.MultipleObjectsReturned: get() returned more than one Garden -- it returned 2!
2018-02-03T18:22:05.803512613Z app[web.1]: Internal Server Error: /plot/12/edit/
2018-02-03T18:22:05.803591770Z app[web.1]: Traceback (most recent call last):
2018-02-03T18:22:05.803602170Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
2018-02-03T18:22:05.803609481Z app[web.1]:     response = get_response(request)
2018-02-03T18:22:05.803615293Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
2018-02-03T18:22:05.803621678Z app[web.1]:     response = self.process_exception_by_middleware(e, request)
2018-02-03T18:22:05.803627387Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
2018-02-03T18:22:05.803633730Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2018-02-03T18:22:05.803639333Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 69, in view
2018-02-03T18:22:05.803681333Z app[web.1]:     return self.dispatch(request, *args, **kwargs)
2018-02-03T18:22:05.803688259Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
2018-02-03T18:22:05.803694502Z app[web.1]:     return super().dispatch(request, *args, **kwargs)
2018-02-03T18:22:05.803700233Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
2018-02-03T18:22:05.803706353Z app[web.1]:     return super().dispatch(request, *args, **kwargs)
2018-02-03T18:22:05.803712078Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
2018-02-03T18:22:05.803785693Z app[web.1]:     return handler(request, *args, **kwargs)
2018-02-03T18:22:05.803793276Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 194, in post
2018-02-03T18:22:05.803799633Z app[web.1]:     return super().post(request, *args, **kwargs)
2018-02-03T18:22:05.803805278Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 141, in post
2018-02-03T18:22:05.803867076Z app[web.1]:     if form.is_valid():
2018-02-03T18:22:05.803876451Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 179, in is_valid
2018-02-03T18:22:05.803882670Z app[web.1]:     return self.is_bound and not self.errors
2018-02-03T18:22:05.803888158Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 174, in errors
2018-02-03T18:22:05.803894208Z app[web.1]:     self.full_clean()
2018-02-03T18:22:05.803899478Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 376, in full_clean
2018-02-03T18:22:05.803932273Z app[web.1]:     self._clean_fields()
2018-02-03T18:22:05.803941267Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 394, in _clean_fields
2018-02-03T18:22:05.803947476Z app[web.1]:     value = field.clean(value)
2018-02-03T18:22:05.803952961Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/fields.py", line 148, in clean
2018-02-03T18:22:05.803961459Z app[web.1]:     value = self.to_python(value)
2018-02-03T18:22:05.803967065Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/models.py", line 1245, in to_python
2018-02-03T18:22:05.803973001Z app[web.1]:     value = self.queryset.get(**{key: value})
2018-02-03T18:22:05.803978459Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 407, in get
2018-02-03T18:22:05.803984296Z app[web.1]:     (self.model._meta.object_name, num)
2018-02-03T18:22:05.803989742Z app[web.1]: gardenhub.models.MultipleObjectsReturned: get() returned more than one Garden -- it returned 2!
2018-02-03T18:22:12.072182210Z app[web.1]: Internal Server Error: /plot/12/edit/
2018-02-03T18:22:12.072219838Z app[web.1]: Traceback (most recent call last):
2018-02-03T18:22:12.072239629Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
2018-02-03T18:22:12.072248372Z app[web.1]:     response = get_response(request)
2018-02-03T18:22:12.072254606Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
2018-02-03T18:22:12.072261383Z app[web.1]:     response = self.process_exception_by_middleware(e, request)
2018-02-03T18:22:12.072267535Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
2018-02-03T18:22:12.072274006Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2018-02-03T18:22:12.072280061Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 69, in view
2018-02-03T18:22:12.072286192Z app[web.1]:     return self.dispatch(request, *args, **kwargs)
2018-02-03T18:22:12.072292121Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
2018-02-03T18:22:12.072298278Z app[web.1]:     return super().dispatch(request, *args, **kwargs)
2018-02-03T18:22:12.072304032Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
2018-02-03T18:22:12.072321952Z app[web.1]:     return super().dispatch(request, *args, **kwargs)
2018-02-03T18:22:12.072347176Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
2018-02-03T18:22:12.072353899Z app[web.1]:     return handler(request, *args, **kwargs)
2018-02-03T18:22:12.072359979Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 194, in post
2018-02-03T18:22:12.072366282Z app[web.1]:     return super().post(request, *args, **kwargs)
2018-02-03T18:22:12.072372176Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 141, in post
2018-02-03T18:22:12.072378449Z app[web.1]:     if form.is_valid():
2018-02-03T18:22:12.072384256Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 179, in is_valid
2018-02-03T18:22:12.072390626Z app[web.1]:     return self.is_bound and not self.errors
2018-02-03T18:22:12.072396409Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 174, in errors
2018-02-03T18:22:12.072402709Z app[web.1]:     self.full_clean()
2018-02-03T18:22:12.072408416Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 376, in full_clean
2018-02-03T18:22:12.072414782Z app[web.1]:     self._clean_fields()
2018-02-03T18:22:12.072420592Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py", line 394, in _clean_fields
2018-02-03T18:22:12.072426856Z app[web.1]:     value = field.clean(value)
2018-02-03T18:22:12.072432599Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/fields.py", line 148, in clean
2018-02-03T18:22:12.072441216Z app[web.1]:     value = self.to_python(value)
2018-02-03T18:22:12.072447166Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/forms/models.py", line 1245, in to_python
2018-02-03T18:22:12.072453659Z app[web.1]:     value = self.queryset.get(**{key: value})
2018-02-03T18:22:12.072459412Z app[web.1]:   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 407, in get
2018-02-03T18:22:12.072465839Z app[web.1]:     (self.model._meta.object_name, num)
2018-02-03T18:22:12.072471566Z app[web.1]: gardenhub.models.MultipleObjectsReturned: get() returned more than one Garden -- it returned 2!

```

**Comment by alexgleason** [comment]
Looks like 9aa093236d8ffe724144f18e408c62091a5dfd9e fixes the issue, but I'm still confused why my test didn't work. I'm going around in circles on this issue. My major mistake at first was assuming I could continue drilling down after applying `union()` to a queryset. After switching that out for a normal `filter()` I forgot to add `distinct()` back in (which I had previously and removed, because it didn't work when attached to `union()`).

Anyway, it works now, but I'm confused why my test didn't fail. So I'm leaving the issue open.
